apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
   
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - app
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: (.+)
      - job_name: 'kubelet'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubelet:10255
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: instance
            replacement: $1:9100
      - job_name: 'cpu-usage'
        scrape_interval: 10s
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
              - frontend.app.svc.cluster.local:80
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: 'container_cpu_usage_seconds_total'
            action: keep
      - job_name: 'kube-state-metrics'
        honor_labels: true
        scrape_interval: 30s
        scrape_timeout: 30s
        metrics_path: /metrics
        scheme: http
        static_configs:
        - targets: ['kube-state-metrics.app.svc.cluster.local:8080']
      
        

