apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - app
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: .*
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        action: keep
        regex: 9100
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: replace
        target_label: container_name
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod_name
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__address__]
        target_label: __address__
        regex: '(.*):9100'
        replacement: 'kube-state-metrics.app.svc.cluster.local:8080'
    - job_name: 'kube-state-metrics'
      scrape_interval: 5s
      scrape_timeout: 5s
      metrics_path: /metrics
      dns_sd_configs:
      - names:
          - kube-state-metrics.app.svc.cluster.local
        type: A
        port: 8080

      
        

