apiVersion: monitoring.coreos.com/v1 # api from prometheus operator
kind: PrometheusRule
metadata:
  name: main-rules
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: monitoring
spec:
  groups:
    - name: main.rules
      rules: 
      - alert: HostHighCPULoad
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 30
        for: 2m
        labels:
          severity: warning
          namespace: monitoring
        annotations:
          description: "CPU load on host is over 30%\n Value = {{ $value }}\n Instance = {{ $labels.instnce }}\n"
          summary: "Host CPU load high"
      - alert: KubernetesPodCrachLooping
        expr: kube_pod_container_status_restarts_total > 5
        for: 0m
        labels:
          severity: critical
          namespace: monitoring
        annotations:
          description: "Pod {{ $labels.pod}} is crach looping\n Value = {{ $value }}"
          summary: "Kubernetes pod crach looping"