---
# Source: kube-prometheus-stack/charts/grafana/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-grafana-clusterrolebinding
  labels:
    helm.sh/chart: grafana-6.51.5
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "9.3.8"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: prometheus-grafana
    namespace: default
roleRef:
  kind: ClusterRole
  name: prometheus-grafana-clusterrole
  apiGroup: rbac.authorization.k8s.io
