---
# Source: kube-prometheus-stack/charts/grafana/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-grafana
  namespace: default
  labels:
    helm.sh/chart: grafana-6.51.5
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "9.3.8"
    app.kubernetes.io/managed-by: Helm
rules: []
